name: Build NodeJs application
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  buildnodejs:
    strategy:
      matrix:
        node-version: [18, 20]
        operating-system: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: checkout code
        uses: actions/checkout@v6
      - name: install nodejs versions of ${{ matrix.node-version }} and npm
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - name: install dependencies using npm
        run: npm install
      - name: run test using npm
        run: npm test
      - name: buid the application using npm
        run: npm run build
      - name: upload artifact from runner tocurrent github directory
        uses: actions/upload-artifact@v7
        with:
          name: build-artifact
          path: /home/runner/work/GithubActions-NodeJs-Demo/GithubActions-NodeJs-Demo/dist/index.html 

