---
name: runtime input demo
on:
  workflow_dispatch:
    inputs:
      runner:
        description: 'choose the runner to run the workflow'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
          - ubuntu-latest
          - windows-latest
          - macos-latest
      job-name:
        description: 'choose th job name to run'
        required: true
        default: 'build-job'
        type: choice
        options:
          - build-job
          - test-job
          - deploy-job
jobs:
  build-job:
    if: ${{ github.event.inputs['job-name'] == 'build-job' }}
    runs-on: ${{ github.event.inputs['runner'] }}
    steps:
      - name: build steps
        run: echo "this is build job and running on ${{ github.event.inputs['runner'] }} runner"
  test-job:
    if: ${{ github.event.inputs['job-name'] == 'test-job' }}
    runs-on: ${{ github.event.inputs['runner'] }}
    steps:
      - name: test steps
        run: echo "this is test job and running on ${{ github.event.inputs['runner'] }} runner"
  deploy-job:
    if: ${{ github.event.inputs['job-name'] == 'deploy-job' }}
    runs-on: ${{ github.event.inputs['runner'] }}
    steps:
      - name: deploy steps
        run: echo "this is deploy job and running on ${{ github.event.inputs['runner'] }} runner"
